name: torfin
description: "torfin"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_libtransmission:
    git:
      url: git@github.com:udyan-dev/flutter_libtransmission.git
      ref: e8eb49d5310683394b17dbd8343a066e7807ca30
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.0.0
  flutter_svg: ^2.0.17
  fuzzywuzzy: ^1.2.0
  get_it: ^8.0.3
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  pretty_bytes: ^6.2.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed_annotation: ^3.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.10.0
  flutter_native_splash: ^2.4.5

flutter_gen:
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAsset

  fonts:
    enabled: true
    outputs:
      class_name: AppFont

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600

    - family: IBMPlexSerif
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSerif-SemiBold.ttf
          weight: 600

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
